POST http://localhost:8080/events
content-type: application/json

{
    "Name": "Test Event",
    "Description": "Test Description",
    "Location": "Test Location",
    "DateTime": "2025-01-01T15:30:00.000Z"
}

